# Generated by Django 3.0.8 on 2020-09-13 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0002_auto_20200913_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
