# Generated by Django 3.0.8 on 2020-09-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20200913_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
